version: "3.9"
services:
  database:
    image: postgres:latest
    container_name: r_db
    restart: always
    env_file:
     - .env
    ports:
     - "5432:5432"
    volumes:
     - data:/var/lib/postgresql/data
    networks:
        - backend

  
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    networks:
      - backend
    links:
        - database
    ports:
    - "4000:4000"
volumes:
  data:
networks:
    backend:
        driver: "bridge"
